name: DJs First Workflow
run-name: ${{ github.actor }} is the hottest MF this side of the south-west
on: [push]
jobs:
  Hello-World:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"